newsPage styles fixes
BlackInHUB/petly-team-project-client pull request #10
Opened 2023-02-02 23:05 UTC by PeterZabila

1. added trim() method to normalization
2. fixed indents between tags
3. fixed shadow in Search block
4. disabled search icon in Search input in order to prevent reload page
5. added limits to description and title of the news

Case you see other bugs let me know

2023-02-03 02:42 UTC, a3avdeev reviewed
как по мне все норм. Это похоже на одну из домашек

2023-02-03 06:37 UTC, PeterZabila commented
> 
по фронту власне у нас нічого нового немає)

2023-02-03 07:52 UTC, BlackInHUB requested changes
Зауваження розписав

2023-02-04 08:20 UTC, BlackInHUB reviewed
Ok

2023-02-04 08:21 UTC, merged